In [41]:
import pandas as pd
import numpy as np

In [42]:
df = pd.read_csv("Merged_Landslide_Data.csv")
df.head()

,Event_ID,Date,State,District,Latitude,Longitude,Season,Rainfall_mm,Elevation_m,Slope_Degree,...,Cranes,Relief_Camps,Evacuated_People,Aid_Amount_INR,Relief_Materials_Tons,Compensation_Provided,Recovery_Days,Power_Outage_Hours,Water_Supply_Disrupted,Communication_Disruption
0,LS-029431,2015-05-17,Manipur,Ukhrul,25.67865,94.21606,Pre-Monsoon,0.0,1374.0,NaN,...,0.0,0.0,0.0,0.0,0.0,No,1.0,0.0,No,No
1,LS-027751,2015-02-04,Himachal Pradesh,Kinnaur,30.88606,77.17932,Winter,12.2,917.2,45.7,...,0.0,0.0,9.0,0.0,0.0,No,1.0,0.0,No,No
2,LS-047783,2024-12-05,Jammu and Kashmir,Ramban,34.61433,74.51911,Winter,38.2,1023.6,25.0,...,0.0,0.0,8.0,0.0,0.0,No,1.0,0.0,No,No
3,LS-010499,2016-10-13,Nagaland,Phek,26.16441,94.18366,Post-Monsoon,NaN,797.8,42.5,...,0.0,0.0,8.0,0.0,0.0,No,0.0,0.0,No,No
4,LS-024748,2013-10-19,Uttarakhand,Chamoli,29.90420,79.92994,NaN,61.1,1063.9,41.1,...,NaN,0.0,19.0,0.0,0.0,No,2.0,0.0,No,No

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48108 entries, 0 to 48107
Data columns (total 52 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Event_ID                    48108 non-null  str
 1   Date                        47216 non-null  str
 2   State                       47212 non-null  str
 3   District                    46247 non-null  str
 4   Latitude                    47001 non-null  float64
 5   Longitude                   46973 non-null  float64
 6   Season                      47172 non-null  str
 7   Rainfall_mm                 45537 non-null  float64
 8   Elevation_m                 46618 non-null  float64
 9   Slope_Degree                46571 non-null  float64
 10  Soil_Type                   46146 non-null  str
 11  NDVI                        46535 non-null  float64
 12  Temperature_C               47149 non-null  float64
 13  Humidity                    47000 non-null  float64
 14  Distance_to_River_km        46693 non-null  float64
 15  Land_Use                    46183 non-null  str
 16  Historical_Landslide_Count  47100 non-null  float64
 17  Landslide_Occurred          47422 non-null  str
 18  Landslide_Risk              46618 non-null  str
 19  Casualties                  45934 non-null  float64
 20  Injured                     46486 non-null  float64
 21  Missing_Persons             46905 non-null  float64
 22  Families_Affected           46239 non-null  float64
 23  Population_Affected         46645 non-null  float64
 24  Houses_Damaged              45988 non-null  float64
 25  Roads_Blocked_km            45994 non-null  float64
 26  Bridges_Damaged             46419 non-null  float64
 27  Economic_Loss_INR           46132 non-null  float64
 28  Cropland_Damaged            46935 non-null  float64
 29  Livestock_Lost              46258 non-null  float64
 30  Response_ID                 48108 non-null  str
 31  Response_Time_Min           46553 non-null  float64
 32  Rescue_Duration_Hours       44493 non-null  float64
 33  Human_Resources_Deployed    45891 non-null  float64
 34  Rescue_Teams                45820 non-null  float64
 35  NDRF_Teams                  46282 non-null  float64
 36  SDRF_Teams                  46740 non-null  float64
 37  Volunteers                  46435 non-null  float64
 38  Ambulances                  47059 non-null  float64
 39  Helicopters                 45654 non-null  float64
 40  Excavators                  45751 non-null  float64
 41  JCB_Machines                45874 non-null  float64
 42  Cranes                      46971 non-null  float64
 43  Relief_Camps                45817 non-null  float64
 44  Evacuated_People            46720 non-null  float64
 45  Aid_Amount_INR              46623 non-null  float64
 46  Relief_Materials_Tons       46612 non-null  float64
 47  Compensation_Provided       47126 non-null  str
 48  Recovery_Days               46731 non-null  float64
 49  Power_Outage_Hours          47035 non-null  float64
 50  Water_Supply_Disrupted      47095 non-null  str
 51  Communication_Disruption    47140 non-null  str
dtypes: float64(39), str(13)
memory usage: 19.1 MB

In [44]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [45]:
float_cols = [
    "Latitude", "Longitude", "Rainfall_mm", "Elevation_m",
    "Slope_Degree", "NDVI", "Temperature_C", "Humidity",
    "Distance_to_River_km", "Roads_Blocked_km",
    "Economic_Loss_INR", "Cropland_Damaged",
    "Response_Time_Min", "Rescue_Duration_Hours",
    "Aid_Amount_INR", "Relief_Materials_Tons",
    "Power_Outage_Hours"
]

for col in float_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [46]:
int_cols = [
    "Historical_Landslide_Count", "Casualties", "Injured",
    "Missing_Persons", "Families_Affected",
    "Population_Affected", "Houses_Damaged",
    "Bridges_Damaged", "Livestock_Lost",
    "Human_Resources_Deployed", "Rescue_Teams",
    "NDRF_Teams", "SDRF_Teams", "Volunteers",
    "Ambulances", "Helicopters", "Excavators",
    "JCB_Machines", "Cranes", "Relief_Camps",
    "Evacuated_People", "Recovery_Days"
]

for col in int_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48108 entries, 0 to 48107
Data columns (total 52 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Event_ID                    48108 non-null  str
 1   Date                        47216 non-null  datetime64[us]
 2   State                       47212 non-null  str
 3   District                    46247 non-null  str
 4   Latitude                    47001 non-null  float64
 5   Longitude                   46973 non-null  float64
 6   Season                      47172 non-null  str
 7   Rainfall_mm                 45537 non-null  float64
 8   Elevation_m                 46618 non-null  float64
 9   Slope_Degree                46571 non-null  float64
 10  Soil_Type                   46146 non-null  str
 11  NDVI                        46535 non-null  float64
 12  Temperature_C               47149 non-null  float64
 13  Humidity                    47000 non-null  float64
 14  Distance_to_River_km        46693 non-null  float64
 15  Land_Use                    46183 non-null  str
 16  Historical_Landslide_Count  47100 non-null  Int64
 17  Landslide_Occurred          47422 non-null  str
 18  Landslide_Risk              46618 non-null  str
 19  Casualties                  45934 non-null  Int64
 20  Injured                     46486 non-null  Int64
 21  Missing_Persons             46905 non-null  Int64
 22  Families_Affected           46239 non-null  Int64
 23  Population_Affected         46645 non-null  Int64
 24  Houses_Damaged              45988 non-null  Int64
 25  Roads_Blocked_km            45994 non-null  float64
 26  Bridges_Damaged             46419 non-null  Int64
 27  Economic_Loss_INR           46132 non-null  float64
 28  Cropland_Damaged            46935 non-null  float64
 29  Livestock_Lost              46258 non-null  Int64
 30  Response_ID                 48108 non-null  str
 31  Response_Time_Min           46553 non-null  float64
 32  Rescue_Duration_Hours       44493 non-null  float64
 33  Human_Resources_Deployed    45891 non-null  Int64
 34  Rescue_Teams                45820 non-null  Int64
 35  NDRF_Teams                  46282 non-null  Int64
 36  SDRF_Teams                  46740 non-null  Int64
 37  Volunteers                  46435 non-null  Int64
 38  Ambulances                  47059 non-null  Int64
 39  Helicopters                 45654 non-null  Int64
 40  Excavators                  45751 non-null  Int64
 41  JCB_Machines                45874 non-null  Int64
 42  Cranes                      46971 non-null  Int64
 43  Relief_Camps                45817 non-null  Int64
 44  Evacuated_People            46720 non-null  Int64
 45  Aid_Amount_INR              46623 non-null  float64
 46  Relief_Materials_Tons       46612 non-null  float64
 47  Compensation_Provided       47126 non-null  str
 48  Recovery_Days               46731 non-null  Int64
 49  Power_Outage_Hours          47035 non-null  float64
 50  Water_Supply_Disrupted      47095 non-null  str
 51  Communication_Disruption    47140 non-null  str
dtypes: Int64(22), datetime64[us](1), float64(17), str(12)
memory usage: 20.1 MB

In [48]:
text_cols = df.select_dtypes(include="str").columns

for col in text_cols:
    df[col] = df[col].str.strip()

In [49]:
df["State"] = df["State"].str.title()

In [50]:
df["Soil_Type"] = df["Soil_Type"].str.strip().str.title()

In [51]:
df.replace(r'^\s*$', np.nan, regex=True, inplace=True)

,Event_ID,Date,State,District,Latitude,Longitude,Season,Rainfall_mm,Elevation_m,Slope_Degree,...,Cranes,Relief_Camps,Evacuated_People,Aid_Amount_INR,Relief_Materials_Tons,Compensation_Provided,Recovery_Days,Power_Outage_Hours,Water_Supply_Disrupted,Communication_Disruption
0,LS-029431,2015-05-17,Manipur,Ukhrul,25.67865,94.21606,Pre-Monsoon,0.0,1374.0,NaN,...,0,0,0,0.0,0.0,No,1,0.0,No,No
1,LS-027751,2015-02-04,Himachal Pradesh,Kinnaur,30.88606,77.17932,Winter,12.2,917.2,45.7,...,0,0,9,0.0,0.0,No,1,0.0,No,No
2,LS-047783,2024-12-05,Jammu And Kashmir,Ramban,34.61433,74.51911,Winter,38.2,1023.6,25.0,...,0,0,8,0.0,0.0,No,1,0.0,No,No
3,LS-010499,2016-10-13,Nagaland,Phek,26.16441,94.18366,Post-Monsoon,NaN,797.8,42.5,...,0,0,8,0.0,0.0,No,0,0.0,No,No
4,LS-024748,2013-10-19,Uttarakhand,Chamoli,29.90420,79.92994,NaN,61.1,1063.9,41.1,...,<NA>,0,19,0.0,0.0,No,2,0.0,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48103,LS-034141,2011-07-26,Mizoram,Lunglei,22.39677,92.98318,Monsoon,449.4,2519.7,22.4,...,0,0,7,0.0,0.0,No,1,0.0,No,No
48104,LS-013928,2009-06-21,Karnataka,Kodagu,11.90904,75.29533,Monsoon,624.4,NaN,33.9,...,4,3,129,4182274.0,3.5,Yes,20,33.2,No,No
48105,LS-000920,2005-07-25,Mizoram,Aizawl,23.07356,93.22014,Monsoon,726.7,1279.1,37.6,...,0,6,<NA>,-2862087.0,25.0,Yes,212,28.2,No,Yes
48106,LS-038468,2009-11-28,Goa,North Goa,15.02519,73.77516,Post-Monsoon,52.9,1735.1,2.1,...,0,0,7,0.0,0.0,No,0,0.0,No,No
48107,LS-010743,2006-08-19,Maharashtra,Ratnagiri,18.08574,73.28401,Monsoon,457.6,1866.0,48.2,...,0,0,3,0.0,0.0,No,1,0.0,No,No

In [52]:
df.dtypes

Event_ID                                 str
Date                          datetime64[us]
State                                    str
District                                 str
Latitude                             float64
Longitude                            float64
Season                                   str
Rainfall_mm                          float64
Elevation_m                          float64
Slope_Degree                         float64
Soil_Type                                str
NDVI                                 float64
Temperature_C                        float64
Humidity                             float64
Distance_to_River_km                 float64
Land_Use                                 str
Historical_Landslide_Count             Int64
Landslide_Occurred                       str
Landslide_Risk                           str
Casualties                             Int64
Injured                                Int64
Missing_Persons                        Int64
Families_Affected                      Int64
Population_Affected                    Int64
Houses_Damaged                         Int64
Roads_Blocked_km                     float64
Bridges_Damaged                        Int64
Economic_Loss_INR                    float64
Cropland_Damaged                     float64
Livestock_Lost                         Int64
Response_ID                              str
Response_Time_Min                    float64
Rescue_Duration_Hours                float64
Human_Resources_Deployed               Int64
Rescue_Teams                           Int64
NDRF_Teams                             Int64
SDRF_Teams                             Int64
Volunteers                             Int64
Ambulances                             Int64
Helicopters                            Int64
Excavators                             Int64
JCB_Machines                           Int64
Cranes                                 Int64
Relief_Camps                           Int64
Evacuated_People                       Int64
Aid_Amount_INR                       float64
Relief_Materials_Tons                float64
Compensation_Provided                    str
Recovery_Days                          Int64
Power_Outage_Hours                   float64
Water_Supply_Disrupted                   str
Communication_Disruption                 str
dtype: object

In [53]:
sorted(df["State"].dropna().unique())

['Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Goa',
 'Himachal Pradesh',
 'Jammu And Kashmir',
 'Karnataka',
 'Kerala',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Sikkim',
 'Tamil Nadu',
 'Uttarakhand',
 'West Bengal']

In [54]:
sorted(df["Soil_Type"].dropna().unique())

['Alluvial', 'Clayey', 'Laterite', 'Loamy', 'Rocky', 'Sandy Loam', 'Silty']

In [55]:
df["Human_Resources_Deployed"].describe()

count      45891.0
mean     17.973023
std       17.51902
min            2.0
25%            6.0
50%           11.0
75%           27.0
max          101.0
Name: Human_Resources_Deployed, dtype: Float64

In [56]:
df.to_csv("Merged_Landslide_Data_Cleaned.csv", index=False)

In [57]:
(df["Aid_Amount_INR"] < 0).sum()

np.int64(51)

In [58]:
df[df["Aid_Amount_INR"] < 0]

,Event_ID,Date,State,District,Latitude,Longitude,Season,Rainfall_mm,Elevation_m,Slope_Degree,...,Cranes,Relief_Camps,Evacuated_People,Aid_Amount_INR,Relief_Materials_Tons,Compensation_Provided,Recovery_Days,Power_Outage_Hours,Water_Supply_Disrupted,Communication_Disruption
876,LS-014597,2008-03-17,Mizoram,Lunglei,23.66286,93.27824,Pre-Monsoon,115.20,1762.6,44.3,...,0,0,0,-1.0,0.0,No,2,0.0,No,No
2620,LS-038953,2021-07-11,Mizoram,Aizawl,23.11799,92.97923,Monsoon,729.60,849.0,20.1,...,0,0,11,-1.0,0.0,No,1,0.0,No,No
2869,LS-024975,2019-12-22,Mizoram,Aizawl,22.84037,93.08220,Winter,29.70,1505.0,31.1,...,0,0,16,-1.0,0.0,No,0,0.0,No,No
2873,LS-003072,2005-06-16,Maharashtra,Ratnagiri,17.16660,73.65620,Monsoon,202.20,1788.7,24.1,...,0,0,4,-1.0,0.0,No,2,0.0,No,No
4723,LS-009899,2013-09-08,Mizoram,Aizawl,22.45927,93.05146,Monsoon,283.70,215.6,16.5,...,0,0,13,-1.0,0.0,No,<NA>,0.0,No,No
4997,LS-006376,2012-08-09,Goa,South Goa,15.73937,73.90139,Monsoon,295.90,2627.8,23.5,...,0,0,19,-1.0,0.0,No,<NA>,0.0,No,No
5186,LS-021454,2011-05-25,Nagaland,Kohima,25.77297,93.87077,Pre-Monsoon,32.20,474.0,25.7,...,0,0,3,-1.0,0.0,No,1,0.0,No,No
6121,LS-021152,2019-08-21,Nagaland,Kohima,26.05468,93.79841,Monsoon,605.20,1261.1,32.5,...,0,0,17,-1.0,0.0,No,0,0.0,No,No
7701,LS-038930,2008-08-07,Himachal Pradesh,Kinnaur,30.66870,77.27750,Monsoon,319.90,1178.0,31.2,...,0,0,10,-1.0,0.0,No,2,0.0,No,No
7757,LS-014619,2021-01-10,Sikkim,Gangtok,28.07272,88.60324,Winter,59.10,699.0,32.5,...,0,0,7,-1.0,0.0,No,1,0.0,No,No
9710,LS-003320,2008-04-26,Uttarakhand,Uttarkashi,30.04755,79.95062,Pre-Monsoon,49.90,2367.5,46.4,...,0,0,57,-3952325.0,0.7,Yes,117,50.2,No,Yes
9745,LS-026145,2017-06-07,Manipur,Churachandpur,25.53274,94.21192,Monsoon,420.90,548.0,28.2,...,0,0,<NA>,-1.0,0.0,No,2,0.0,No,No
10295,LS-032580,2025-06-13,Assam,Cachar,25.74875,93.05068,Monsoon,569.80,2234.5,38.6,...,0,0,13,-1.0,0.0,No,0,0.0,No,No
11285,LS-021134,2020-03-07,Sikkim,East Sikkim,27.01421,88.19033,Pre-Monsoon,65.80,981.4,18.6,...,0,<NA>,7,-1.0,0.0,No,1,0.0,No,No
11340,LS-024962,2007-06-25,Goa,South Goa,NaN,74.13137,Monsoon,632.30,465.3,42.5,...,0,0,16,-1.0,0.0,No,2,0.0,No,No
11891,LS-038827,2008-04-25,Uttarakhand,Tehri Garhwal,31.21361,79.81466,Pre-Monsoon,46.10,1887.1,14.1,...,0,0,12,-1.0,0.0,No,1,0.0,No,No
12049,LS-048560,2013-07-24,West Bengal,Darjeeling,26.64916,88.81387,Monsoon,87.52,88.3,40.3,...,1,7,133,-3810791.0,11.0,Yes,185,45.5,Yes,Yes
12165,LS-028789,2014-05-30,Nagaland,Phek,26.19013,94.29656,Pre-Monsoon,106.50,2711.3,13.0,...,0,0,7,-1.0,0.0,No,1,0.0,No,No
13430,LS-011724,2005-04-17,Uttarakhand,Rudraprayag,31.04476,77.86162,Pre-Monsoon,133.50,1449.4,27.8,...,0,0,3,-1.0,NaN,No,2,0.0,No,No
13590,LS-028743,2013-11-09,Andhra Pradesh,Alluri Sitharama Raju,17.64984,82.18538,Post-Monsoon,163.20,2903.4,41.4,...,3,<NA>,73,-2255701.0,5.7,Yes,67,34.4,Yes,No
14089,LS-034581,2022-05-26,Odisha,Gajapati,18.67065,82.34414,Pre-Monsoon,24.90,999.1,31.0,...,0,0,17,-1.0,0.0,No,0,0.0,No,No
15076,LS-030653,2021-05-29,Odisha,Gajapati,19.26088,82.56341,Pre-Monsoon,167.50,1005.9,35.8,...,1,4,113,-4053341.0,35.3,Yes,106,82.1,No,Yes
15428,LS-021075,2019-02-12,Sikkim,North Sikkim,27.84009,88.37422,Winter,0.00,1351.2,51.0,...,0,4,62,-6474879.0,9.2,No,186,27.4,Yes,Yes
15954,LS-013695,2006-11-08,Himachal Pradesh,Shimla,30.68325,76.32978,Post-Monsoon,224.00,2894.9,25.3,...,0,0,8,-1.0,0.0,No,1,0.0,No,No
16042,LS-006581,2018-06-04,Maharashtra,Satara,18.89046,73.68636,Monsoon,630.80,929.3,42.8,...,2,4,101,-839164.0,12.7,Yes,75,24.5,Yes,No
17103,LS-001872,2025-02-18,Sikkim,Gangtok,27.82380,88.13105,Winter,17.80,128.8,40.0,...,0,<NA>,5,-1.0,0.0,No,1,0.0,No,No
18426,LS-021059,2014-04-02,Nagaland,Phek,26.25975,94.47749,Pre-Monsoon,132.90,390.5,21.8,...,0,<NA>,15,-1.0,NaN,No,2,0.0,No,No
19058,LS-021192,2006-02-20,Maharashtra,Ratnagiri,18.55365,73.69563,Winter,7.80,2081.3,21.8,...,1,2,56,-2216782.0,12.1,No,109,16.1,No,No
20993,LS-028675,2012-09-07,Assam,Karbi Anglong,25.79410,93.03424,Monsoon,347.70,1408.3,35.3,...,1,6,98,-7713100.0,43.9,Yes,167,8.5,Yes,No
21195,LS-002384,2012-05-01,Karnataka,Kodagu,12.66057,75.16891,Pre-Monsoon,114.90,195.8,33.1,...,0,0,6,-1.0,0.0,No,0,0.0,No,No
22217,LS-047926,2021-06-01,Mizoram,Aizawl,22.46550,93.02034,Monsoon,NaN,653.4,34.4,...,2,2,119,-2525637.0,30.0,Yes,208,20.1,No,No
24337,LS-021320,2025-05-11,Maharashtra,Satara,16.86028,72.88850,Pre-Monsoon,39.90,2653.7,27.9,...,0,0,12,-1.0,0.0,No,1,0.0,No,No
24914,LS-012454,2010-11-15,Maharashtra,Satara,18.42676,72.82433,Post-Monsoon,215.10,1700.6,36.9,...,0,0,17,-1.0,0.0,No,1,0.0,No,No
26084,LS-039788,2013-02-02,Maharashtra,Raigad,16.50018,73.58771,Winter,11.70,1933.7,24.3,...,0,0,7,-1.0,0.0,No,2,0.0,No,No
26376,LS-041492,2013-05-17,Odisha,Gajapati,18.51841,83.00455,Pre-Monsoon,163.70,1778.3,35.7,...,0,<NA>,4,-1.0,0.0,No,1,0.0,No,No
27618,LS-023926,2007-02-12,Manipur,Churachandpur,25.14741,94.66536,NaN,33.70,2335.0,34.5,...,0,0,11,-1.0,0.0,No,1,0.0,No,No
28439,LS-015333,2022-06-01,Arunachal Pradesh,Papum Pare,27.61651,95.13580,Monsoon,389.70,2552.7,NaN,...,2,2,95,-3662560.0,28.2,Yes,34,5.3,No,No
29699,LS-009906,2018-07-01,West Bengal,Darjeeling,26.44555,88.60020,Monsoon,472.20,2055.8,52.3,...,0,0,14,-1.0,0.0,No,2,0.0,No,No
29708,LS-020896,NaT,Himachal Pradesh,Kullu,30.60943,76.11163,Post-Monsoon,13.88,1047.6,18.2,...,0,0,13,-1.0,0.0,No,0,0.0,No,No
32293,LS-018241,2011-08-01,Meghalaya,East Khasi Hills,25.32889,91.70344,Monsoon,391.80,20.0,26.5,...,3,0,106,-3330158.0,53.5,Yes,28,11.4,No,No
32336,LS-019201,2025-09-30,Sikkim,North Sikkim,27.94791,88.57792,Monsoon,726.70,NaN,45.4,...,4,3,137,-3581400.0,7.1,Yes,226,10.2,No,No
32614,LS-011971,2020-12-07,Nagaland,NaN,26.49427,94.15689,Winter,35.40,500.5,39.6,...,0,0,16,-1.0,0.0,No,2,0.0,No,No
33041,LS-011860,2012-10-05,Uttarakhand,NaN,NaN,77.54580,Post-Monsoon,132.20,625.4,23.5,...,0,0,5,-1.0,0.0,No,2,0.0,No,No
35208,LS-038737,2023-02-21,Arunachal Pradesh,West Kameng,27.17442,94.32575,Winter,15.50,873.9,28.7,...,3,1,40,-1866049.0,0.2,No,32,4.2,Yes,No
37225,LS-025559,2007-02-06,Mizoram,Aizawl,NaN,92.92382,Winter,52.30,647.4,38.8,...,0,0,<NA>,-1.0,0.0,No,0,0.0,No,No
38113,LS-028720,2013-09-15,Maharashtra,NaN,17.24847,73.46175,Monsoon,796.30,1252.1,24.8,...,0,0,1,-1.0,0.0,No,0,0.0,No,No
38680,LS-029442,2011-08-30,Goa,South Goa,15.66229,73.72566,Monsoon,NaN,1341.4,31.4,...,0,0,5,-1.0,0.0,No,0,0.0,No,No
40208,LS-041472,2019-02-03,Mizoram,Aizawl,22.95908,92.97412,Winter,52.10,944.1,61.4,...,0,0,10,-1.0,0.0,No,1,0.0,No,No
41690,LS-038849,2024-10-18,Himachal Pradesh,Kullu,32.15692,78.02195,Post-Monsoon,92.50,1246.0,18.0,...,3,4,26,-161070.0,4.9,Yes,115,1.1,Yes,Yes
43147,LS-037663,2022-03-18,Mizoram,Aizawl,23.10578,93.26638,Pre-Monsoon,98.60,2445.2,25.0,...,0,0,7,-1.0,0.0,No,2,0.0,No,No
48105,LS-000920,2005-07-25,Mizoram,Aizawl,23.07356,93.22014,Monsoon,726.70,1279.1,37.6,...,0,6,<NA>,-2862087.0,25.0,Yes,212,28.2,No,Yes

In [59]:
import numpy as np

df.loc[df["Aid_Amount_INR"] < 0, "Aid_Amount_INR"] = np.nan

In [60]:
(df["Aid_Amount_INR"] < 0).sum()

np.int64(0)

In [61]:
df["Aid_Amount_INR"].isna().sum()

np.int64(1536)

In [62]:
df["State"] = df["State"].fillna(df["State"].mode()[0])

In [63]:
df["Soil_Type"] = df["Soil_Type"].fillna(df["Soil_Type"].mode()[0])

In [64]:
df["Human_Resources_Deployed"] = df["Human_Resources_Deployed"].fillna(
    df["Human_Resources_Deployed"].median()
)

In [65]:
print("State:", df["State"].isna().sum())
print("Soil_Type:", df["Soil_Type"].isna().sum())
print("Human_Resources_Deployed:", df["Human_Resources_Deployed"].isna().sum())

State: 0
Soil_Type: 0
Human_Resources_Deployed: 0

In [66]:
df.to_csv("Merged_Landslide_Data_Cleaned.csv", index=False)